-- This file is automatically generated, changes will likely be overriden.

local M = {}

function M.print_rule(lua_rule)
    return print_rule(lua_rule)
end

function M._create_default_rule()
    return _create_default_rule()
end

return M
