-- This file is generated by Templar. Do not edit it manually.

local M = {}
function M.print_rule(lua_rule)
	return print_rule(lua_rule)
end

function M._create_default_rule()
	return _create_default_rule()
end


return M
