[package]
name = "lua-export"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.86", features = [ "full" ] }
quote = "1.0.16"
rlua = "0.19.1"
tempdir = "0.3.7"
indoc = "1.0.6"
