[package]
name = "templar"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
lazy_static = "1.4.0"
indoc = "1.0.6"
tempdir = "0.3.7"

[dependencies]
anyhow = "1.0.*"
glob = "0.3.*"
nom = "7.1.*"
rlua = "0.19.*"
lua-export = { path = "../lua-export" }
structopt = "0.3.*"
dyn-clone = "1.0.5"
